session_name: personal
windows:
  - window_name: "home"
    start_directory: "~"
    focus: true
    panes:
      - neofetch
  - window_name: "bootstrap"
    start_directory: "~/.dotfiles"
    panes:
      -
