session_name: personal
windows:
  - window_name: "main"
    start_directory: "~"
    focus: true
    panes:
      - neofetch
  - window_name: "bootstrap"
    start_directory: "~/Workspace/bootstrap"
    panes:
      -
