session_name: "vt"
start_directory: "~/Workspace/vt/"
windows:
  - window_name: "main"
    start_directory: "~"
    focus: true
    panes:
      -

  - window_name: "varsitytutors"
    start_directory: "vt"
    panes:
      -
