session_name: zee
windows:
  - window_name: "main"
    start_directory: "~"
    focus: true
    panes:
      -
  - window_name: storefront
    start_directory: "~/workspace/zee/storefront"
    panes:
      -
  - window_name: dispatch
    start_directory: "~/workspace/zee/dispatch"
    panes:
      -
  - window_name: stock
    start_directory: "~/workspace/zee/stock"
    panes:
      -
  - window_name: petz
    start_directory: "~/workspace/zee/petz"
    panes:
      -
  - window_name: portal
    start_directory: "~/workspace/zee/portal"
    panes:
      -
  - window_name: authy
    start_directory: "~/workspace/zee/authy"
    panes:
      -
  - window_name: ifood
    start_directory: "~/workspace/zee/ifood"
    panes:
      -
