session_name: zee
windows:
  - window_name: "main"
    start_directory: "~"
    focus: true
    panes:
      -
  - window_name: storefront
    start_directory: "~/Workspace/zee/storefront"
    panes:
      -
  - window_name: dispatch
    start_directory: "~/Workspace/zee/dispatch"
    panes:
      -
  - window_name: stock
    start_directory: "~/Workspace/zee/stock"
    panes:
      -
  - window_name: warehouse
    start_directory: "~/Workspace/zee/warehouse"
    panes:
      -
  - window_name: portal
    start_directory: "~/Workspace/zee/portal"
    panes:
      -
  - window_name: auth
    start_directory: "~/Workspace/zee/auth"
    panes:
      -
  - window_name: ifood
    start_directory: "~/Workspace/zee/ifood"
    panes:
      -
